backend:
  name: github
  repo: asmmarkettrader-design/asmmarkettrader-design.github.io
  branch: main
  site_url: https://www.asmveo.com

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
