backend:
  name: github
  repo: آپ_کا_گٹ_ہب_یوزر_نیم/آپ_کی_ریپوزٹری_کا_نام # یہاں اپنا نام لکھیں
  branch: main # یا master جو بھی آپ کی برانچ کا نام ہے

media_folder: "images/uploads" # جو تصویریں آپ اپلوڈ کریں گے وہ یہاں جائیں گی
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "_pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
